title: Window to the World
author: JaronTrey4
email: jaron.jedlicka@lexisnexisrisk.com
description: > # this means to ignore newlines until "baseurl:"
This site is very introductory and beginner-level.

theme: minima

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
